spring:
  profiles: production
    jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    generate-ddl: false
    properties:
    hibernate.id.new_generator_mappings: true
    hibernate.cache.use_second_level_cache: false
    hibernate.cache.use_query_cache: false
    hibernate.generate_statistics: true
  data:
    host: localhost
    port: 27017
    database: user
    username: root
    password: 111111
    uri: mongodb://name:pass@localhost:27017/user

